const LEET = {'0':'o','1':'i','2':'z','3':'e','4':'a','5':'s','6':'b','7':'t','8':'b','9':'g','@':'a','!':'i','$':'s','+':'t','|':'i','(':'c',')':'o','<':'c','>':'o'};
function normalize(str) {
  let s = String(str||'').toLowerCase();
  s = s.split('').map(c=>LEET[c]!==undefined?LEET[c]:c).join('');
  return s.replace(/[^a-z]/g,'');
}
function levenshtein(a,b){
  const m=a.length,n=b.length;
  if(m===0)return n;if(n===0)return m;
  const dp=Array.from({length:m+1},(_,i)=>[i]);
  for(let j=1;j<=n;j++)dp[0][j]=j;
  for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)dp[i][j]=a[i-1]===b[j-1]?dp[i-1][j-1]:1+Math.min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1]);
  return dp[m][n];
}
function maxEdits(len){if(len<=5)return 0;if(len<=8)return 1;return 2;}
function fuzzyContains(text,word){
  const wLen=word.length,maxE=maxEdits(wLen);
  if(maxE===0)return text.includes(word);
  for(let winLen=Math.max(1,wLen-maxE);winLen<=wLen+maxE;winLen++)
    for(let i=0;i<=text.length-winLen;i++)
      if(levenshtein(text.slice(i,i+winLen),word)<=maxE)return true;
  return false;
}

const BLOCKED = ['fuck','fucker','fuckers','fucking','fucked','fuckwit','fuckhead','fuckface','motherfucker','motherfucking','clusterfuck','mindfuck','shithead','bullshit','dipshit','horseshit','shitstain','shitface','shitbag','shithole','bitch','bitches','bitching','bitchass','cunt','cunts','cunting','cocksucker','cocksucking','asshole','assholes','asshat','asswipe','assbag','assclown','assfuck','dickhead','dickheads','dickwad','dickweed','dickface','dickbag','wanker','wankers','wanking','bastard','bastards','douchebag','douchebags','blowjob','blowjobs','handjob','handjobs','cumshot','cumshots','rimjob','rimjobs','titfuck','titfucking','fuckboy','fuckboys','fuckgirl','fuckgirls','slutbag','whorebag','skank','skanks','skanky','nigger','niggers','nigga','niggas','niggaz','spick','spics','spicks','wetback','wetbacks','chinks','kike','kikes','towelhead','towelheads','zipperhead','zipperheads','beaner','beaners','whitepride','whitepower','whitesupremacist','whitesupremacy','whitenationalist','whitenationalism','kukluxklan','neonazi','neonazis','nazism','faggot','faggots','faggotry','tranny','trannies','shemale','shemales','pornography','porno','pornstar','pornstars','dildo','dildos','buttplug','buttplugs','analbeads','fleshlight','fleshlights','sexdoll','sexdolls','masturbator','masturbators','masturbation','cockring','cockrings','strapon','strapons','genocide','ethniccleansing','lynching','racewar','racewars','hategroup','hategroups','putangina','putanginamo','kinginamo','kingina','tarantado','tarantadong','walanghiya','walangkahiyahiya','pakantot','pakantutan','nagkantot','nagkantutan','kantotin','kantutan','magkantot','jakulin','jakulan','magjakol','nagjajakol','iyotin','iyutan','magiyot','nagiyot','giiyot','giiyutan','hindotin','hindutan','maghindot','naghindot','malibog','malibugin','naglibog','pokpok','pokpokin','burikat','burikaton','pakshet','pakshetan','pakshit','pakshitin','yatutan','giatay','giatayan','gikantot','gikantutan','pakantota','pakantotaha','malandihin','malaswa','malaswang','mahalay','mahalayin','bastosin','gunggong','gunggongin','mangmang','mangmangin','estupido','estupida','hambogero','mayabang','mayabangng','salbahe','salbaheng','bayotin','kabayot','badingin','supotin','supotan','kupalin','kupaling','tamodin','itamod','utongin','buratin','buratang','botohon','puking','ipuke','bilatin','bilatang','pepeng','ipepe','pweting','ipwet','puwitin','susong','isuso','titihin','tititin','etitsin','ototin','umotot','dagahin','hayopang','unggoying','baboyng','bungotang','engoteng','inutilang','bwisitin','lintikan','pistihan','pistiha','buangon','kabuang','bogoa','kabogo','boanga','kaboang','hungog','hungoging','hubogin','kahubog','otenan','otinan','pisotan','kinsehon','iyoton','iyoten','buraten','pukien','titien','tamoden','napaitanen','gagohon','gaguen','gaguin','gagohin','tangahon','tangain','tangaen','buangen','ulunen','ulunan','pakyuen','punyetaen','burian','putuan','hindoton','animalon','putahan'];

const SAFE_RAW = ['assorted','assortment','ambassador','passage','classic','grasshopper','harassment training','sexual harassment policy','nutcracker','cracker paper','firecracker','cracker barrel','knee massager','back massager','neck massager','foot massager','hand massager','eye massager','scalp massager','shoulder massager','body massager','muscle massager','percussion massager','paper cutter','box cutter','grass cutter','wire cutter','bolt cutter','nail cutter','tile cutter','glass cutter','carpet cutter','foam cutter','pipe cutter','bottom','bottomless','bottle','bottled','suspension','suspender','titanium','titration','title','titular','pistil','pistol','piston','animal glue','animal feed','animal care','tonic','tonics','toner','burrito','burlap','bureau','kinetics','kinetic','notation','notable','donation','donated','isolation','isolated','taekwondo','tape','taper','tapestry','inhibitor','inhibit','botanical','botany','attic','attach','attachment','static','station','stationery','elastic','elasticity','plastic','plastics','fantastic','fantasy','domestic','domestics','athletic','athletics','synthetic','synthetics','antiseptic','antiseptics','magnetic','magnetics','electric','electrical','electricity','hydraulic','hydraulics','pneumatic','pneumatics','automatic','automatics','systematic','systematics','problematic','problematics','diplomatic','diplomatics','aromatic','aromatics','chromatic','chromatics','dramatic','dramatics','traumatic','traumatics','schematic','schematics','thematic','thematics','symptomatic','symptomatics','asthmatic','asthmatics','charismatic','charismatics','idiomatic','idiomatics','axiomatic','axiomatics','prismatic','prismatics','enzymatic','enzymatics','cinematic','cinematics','panoramic','panoramics','ceramic','ceramics','dynamic','dynamics','organic','organics','mechanic','mechanics','botanic','botanics','volcanic','volcanics','galvanic','galvanics','titanic','titanics','satanic','satanics','oceanic','oceanics','hispanic','hispanics','islamic','islamics','mosaic','mosaics','prosaic','prosaics','archaic','archaics','algebraic','algebraics','stochastic','stochastics','elastic band','elastic cord','elastic rope'];

function isSafe(raw) {
  const lower = raw.toLowerCase();
  return SAFE_RAW.some(p => lower.includes(p));
}
function isOffensive(input) {
  if (!input) return false;
  if (isSafe(input)) return false;
  const token = normalize(input);
  if (!token || token.length < 3) return false;
  for (const blocked of BLOCKED) {
    if (fuzzyContains(token, blocked)) return true;
  }
  return false;
}

const SUPPLY_ITEMS = [
  'ballpen','ballpoint pen','bond paper','folder','stapler','staple wire',
  'scotch tape','masking tape','correction tape','rubber band','paper clip',
  'binder clip','push pin','thumbtack','scissors','cutter','ruler',
  'calculator','whiteboard marker','permanent marker','highlighter',
  'sticky note','index card','envelope','mailing envelope','kraft paper',
  'carbon paper','tracing paper','construction paper','colored paper',
  'tissue paper','toilet paper','paper towel','facial tissue',
  'alcohol','isopropyl alcohol','ethyl alcohol','hand sanitizer',
  'dishwashing liquid','floor wax','bleach','disinfectant','detergent',
  'garbage bag','trash bag','plastic bag','ziplock bag',
  'broom','dustpan','mop','floor mop','wiper','squeegee',
  'pail','bucket','basin','dipper','ladle',
  'extension cord','power strip','electrical tape','wire','cable',
  'battery','alkaline battery','rechargeable battery',
  'light bulb','fluorescent lamp','led bulb','cfl bulb',
  'printer ink','toner cartridge','ink cartridge','ribbon',
  'usb flash drive','memory card','cd','dvd','hard disk',
  'mouse','keyboard','monitor','laptop','desktop','tablet',
  'hdmi cable','vga cable','ethernet cable','lan cable',
  'padlock','door knob','door hinge','screw','nail','bolt','nut',
  'hammer','pliers','screwdriver','wrench','drill bit',
  'paint brush','roller brush','paint tray','sandpaper',
  'measuring tape','level','square','compass',
  'first aid kit','bandage','gauze','cotton','antiseptic',
  'thermometer','blood pressure monitor','pulse oximeter',
  'face mask','surgical mask','n95 mask','gloves','goggles',
  'fire extinguisher','smoke detector','safety vest',
  'whiteboard','corkboard','bulletin board','chalkboard',
  'chair','table','desk','cabinet','shelf','rack','locker',
  'curtain','blinds','window screen','door mat','floor mat',
  'air freshener','deodorizer','insect repellent','rat trap',
  'staple remover','hole punch','paper shredder','laminator',
  'binding machine','paper cutter','guillotine cutter',
  'ink pad','stamp','date stamp','rubber stamp',
  'correction fluid','white out','liquid paper',
  'glue stick','paste','adhesive','super glue','epoxy',
  'tape dispenser','letter opener',
  'document tray','file tray','inbox tray','outbox tray',
  'magazine holder','book end','book stand',
  'pen holder','pencil cup','desk organizer',
  'name plate','name tag','id holder','lanyard',
  'presentation folder','report cover','binder','ring binder',
  'divider','tab divider','index tab',
  'notebook','composition notebook','spiral notebook','pad paper',
  'logbook','record book','register','ledger',
  'pencil','mechanical pencil','colored pencil','crayon',
  'eraser','pencil eraser','kneaded eraser',
  'sharpener','pencil sharpener','electric sharpener',
  'ruler','triangle ruler','protractor',
  'globe','map','atlas','dictionary','encyclopedia',
  'clock','wall clock','desk clock','timer',
  'calendar','planner','organizer','agenda',
  'frame','picture frame','certificate frame',
  'tarpaulin','banner','streamer','bunting',
  'ribbon','gift wrap','wrapping paper','bow',
  'candle','matches','lighter',
  'umbrella','raincoat','rain boots',
  'bag','backpack','sling bag','tote bag','briefcase',
  'water bottle','tumbler','thermos','mug','cup',
  'plate','bowl','spoon','fork','knife','chopsticks',
  'food container','lunch box','bento box',
  'coffee maker','electric kettle','microwave','refrigerator',
  'fan','electric fan','stand fan','desk fan','ceiling fan',
  'air conditioner','air purifier','humidifier','dehumidifier',
  'vacuum cleaner','carpet sweeper','floor polisher',
  'washing machine','dryer','iron','ironing board',
  'sewing kit','needle','thread','thimble',
  'measuring cup','measuring spoon','kitchen scale',
  'cutting board','chopping board',
  'plastic wrap','aluminum foil','wax paper','parchment paper',
  'rubber gloves','latex gloves','nitrile gloves',
  'safety pin','straight pin','sewing pin',
  'velcro','hook and loop','cable tie','zip tie',
  'bubble wrap','packing tape','packing foam','styrofoam',
  'cardboard box','corrugated box','mailer box',
  'label','sticker','price tag','barcode label',
  'receipt paper','thermal paper','fax paper',
  'projector','projector screen','laser pointer',
  'whiteboard eraser','chalk','chalk eraser',
  'easel','flip chart','flip chart paper',
  'extension ladder','step ladder','step stool',
  'toolbox','tool kit','utility knife',
  'magnifying glass','loupe','microscope',
  'weighing scale','platform scale','postal scale',
  'paper weight','bookweight',
  'document holder','copy holder',
  'wrist rest','mouse pad','keyboard tray',
  'monitor stand','laptop stand','tablet stand',
  'phone stand','tablet holder','book holder',
  'cable organizer','cable management','cable sleeve',
  'surge protector','ups','uninterruptible power supply',
  'power bank','solar charger','wireless charger',
  'bluetooth speaker','headphone','earphone','microphone',
  'webcam','document camera','scanner','printer',
  'photocopier','fax machine','telephone','intercom',
  'shredder','paper shredder','cross cut shredder',
  'safe','vault','cash box','money box',
  'coin sorter','bill counter','money counter',
  'credit card reader','pos terminal','barcode scanner',
  'label maker','label printer','thermal printer',
  'receipt printer','dot matrix printer','inkjet printer',
  'laser printer','multifunction printer',
  'bolpen','lapis','papel','gunting','pandikit','pita',
  'walis','walis tambo','walis tingting','basahan',
  'timba','tabo','balde','palanggana',
  'kandila','posporo',
  'unan','kumot','tuwalya','sabon','shampoo',
  'toothbrush','toothpaste','dental floss',
  'cotton buds','cotton balls','gauze pad',
  'plaster','bandaid','band aid',
  'rubbing alcohol','betadine','hydrogen peroxide',
  'paracetamol','aspirin','ibuprofen','vitamins',
  'insecticide','pesticide','rodenticide','herbicide',
  'fertilizer','potting soil','garden soil',
  'plant pot','flower pot','seedling tray',
  'garden hose','sprinkler','watering can',
  'rake','shovel','spade','trowel','hoe',
  'pruning shears','hedge trimmer','lawn mower',
  'rope','twine','string','chain',
  'door stopper','door wedge','door closer',
  'window latch','window lock','window handle',
  'curtain rod','curtain ring','curtain hook',
  'picture hook','wall hook','coat hook',
  'shelf bracket','wall bracket','angle bracket',
  'wood screw','machine screw','self tapping screw',
  'anchor bolt','expansion bolt','toggle bolt',
  'washer','flat washer','spring washer','lock washer',
  'hex nut','wing nut','cap nut',
  'carriage bolt','hex bolt','eye bolt',
  'rivet','pop rivet','blind rivet',
  'hinge','butt hinge','piano hinge','spring hinge',
  'latch','door latch','gate latch','barrel bolt',
  'handle','door handle','cabinet handle','drawer pull',
  'caster','wheel','roller','glide','foot pad',
  'rubber foot','rubber bumper','rubber stopper',
  'felt pad','furniture pad','floor protector',
  'drawer liner','shelf liner','cabinet liner',
  'contact paper','shelf paper','drawer paper',
  'emery cloth','steel wool','scouring pad',
  'paint','primer','varnish','lacquer','enamel',
  'thinner','solvent','turpentine','mineral spirits',
  'caulk','sealant','grout','putty','filler',
  'lubricant','grease','oil','wd40','penetrating oil',
  'cleaning cloth','microfiber cloth','chamois','sponge',
  'scrub brush','bottle brush','toilet brush','grout brush',
  'mop head','mop handle','mop bucket','wringer',
  'broom handle','broom head','dustpan','lobby dustpan',
  'trash can','waste bin','recycling bin','compost bin',
  'garbage bag','trash liner','bin liner',
  'moth ball','moth repellent','cedar block',
  'rat trap','mouse trap','glue trap','snap trap',
  'fly swatter','fly paper','fly trap','insect trap',
  'mosquito coil','mosquito net','mosquito repellent',
  'cockroach bait','ant bait','termite bait',
  'disinfectant spray','sanitizing spray','germicide',
  'bleach','chlorine','sodium hypochlorite',
  'muriatic acid','hydrochloric acid','sulfuric acid',
  'baking soda','sodium bicarbonate','washing soda',
  'borax','oxalic acid','citric acid','vinegar',
  'dish soap','dishwashing soap','hand soap','bar soap',
  'laundry soap','laundry detergent','fabric softener',
  'stain remover','bleach pen','color safe bleach',
  'floor cleaner','tile cleaner','bathroom cleaner',
  'glass cleaner','window cleaner','mirror cleaner',
  'furniture polish','wood polish','metal polish',
  'shoe polish','leather conditioner','suede cleaner',
  'carpet cleaner','upholstery cleaner','fabric cleaner',
  'degreaser','engine cleaner','brake cleaner',
  'rust remover','rust converter','rust inhibitor',
  'paint remover','paint stripper','chemical stripper',
  'adhesive remover','glue remover','sticker remover',
  'label remover','tape remover','residue remover',
  'correction tape','masking tape','double sided tape',
  'duct tape','electrical tape','foam tape','mounting tape',
  'transparent tape','invisible tape','magic tape',
  'staple gun','staple remover','staple wire',
  'hole punch','two hole punch','three hole punch',
  'paper fastener','brass fastener','binder clip',
  'bulldog clip','foldback clip','spring clip',
  'rubber band','elastic band','hair band',
  'push pin','map pin','drawing pin','thumbtack',
  'correction pen','correction roller','correction tape',
  'highlighter pen','fluorescent marker','neon marker',
  'permanent marker','whiteboard marker','chalk marker',
  'gel pen','ballpoint pen','rollerball pen','fountain pen',
  'felt tip pen','fiber tip pen','sign pen',
  'mechanical pencil','propelling pencil','clutch pencil',
  'pencil lead','pencil refill','eraser refill',
  'pencil case','pen case','pencil box','pen box',
  'pencil roll','pen roll','pencil pouch','pen pouch',
  'desk pad','writing pad','memo pad','note pad',
  'sticky pad','self stick note','repositionable note',
  'index card','flash card','record card','filing card',
  'file folder','hanging folder','suspension folder',
  'expanding folder','accordion folder','concertina folder',
  'document wallet','document sleeve','document protector',
  'page protector','sheet protector','plastic sleeve',
  'ring binder','lever arch file','box file','magazine file',
  'file divider','index divider','tab divider',
  'label holder','label insert','label strip',
  'file label','folder label','binder label',
  'address label','return address label','shipping label',
  'name badge','name tag','visitor badge','id badge',
  'badge holder','id holder','card holder','badge reel',
  'lanyard','neck strap','badge clip','badge pin',
  'desk calendar','wall calendar','pocket calendar',
  'academic planner','weekly planner','daily planner',
  'appointment book','diary','journal','notebook',
  'composition book','exercise book','spiral bound notebook',
  'hardcover notebook','softcover notebook','wirebound notebook',
  'graph paper','grid paper','lined paper','blank paper',
  'ruled paper','college ruled','wide ruled','narrow ruled',
  'copy paper','bond paper','multipurpose paper','printer paper',
  'cardstock','card paper','cover stock','bristol board',
  'construction paper','art paper','drawing paper','sketch paper',
  'watercolor paper','pastel paper','charcoal paper',
  'origami paper','tissue paper','crepe paper','rice paper',
  'vellum paper','tracing paper','transfer paper','carbon paper',
  'photo paper','glossy paper','matte paper','satin paper',
  'label paper','sticker paper','decal paper','transfer paper',
  'envelope','window envelope','padded envelope','bubble envelope',
  'kraft envelope','manila envelope','catalog envelope',
  'booklet envelope','policy envelope','open end envelope',
  'open side envelope','clasp envelope','button string envelope',
  'mailing tube','postal tube','document tube','shipping tube',
  'bubble mailer','poly mailer','padded mailer','rigid mailer',
  'shipping box','moving box','storage box','archive box',
  'file box','banker box','record box','document box',
  'magazine box','periodical box','newspaper box',
  'display box','counter display','point of sale display',
  'brochure holder','leaflet holder','literature holder',
  'business card holder','business card stand','card display',
  'sign holder','sign stand','sign frame','sign post',
  'poster frame','poster holder','poster stand','poster rail',
  'notice board','pin board','memo board','message board',
  'magnetic board','magnetic whiteboard','glass whiteboard',
  'projection screen','pull down screen','electric screen',
  'flip chart stand','easel pad','presentation pad',
  'laser pointer','presentation remote','clicker',
  'document camera','visualizer','overhead projector',
  'interactive whiteboard','smart board','touch screen display',
  'video conferencing','webcam','conference camera',
  'speakerphone','conference phone','desk phone','ip phone',
  'headset','telephone headset','wireless headset',
  'dictaphone','voice recorder','digital recorder',
  'calculator','scientific calculator','financial calculator',
  'printing calculator','adding machine','cash register',
  'barcode scanner','qr code scanner','rfid reader',
  'label printer','barcode printer','receipt printer',
  'card printer','id card printer','badge printer',
  'time clock','time recorder','attendance machine',
  'fingerprint scanner','biometric scanner','access control',
  'cctv camera','security camera','ip camera','dome camera',
  'dvr','nvr','video recorder','surveillance system',
  'alarm system','motion sensor','door sensor','window sensor',
  'fire alarm','smoke alarm','heat detector','co detector',
  'emergency light','exit sign','safety sign','warning sign',
  'first aid box','medicine cabinet','emergency kit',
  'stretcher','wheelchair','crutches','walking stick',
  'safety helmet','hard hat','bump cap','safety cap',
  'safety glasses','safety goggles','face shield','welding mask',
  'ear plug','ear muff','hearing protection','noise canceling',
  'dust mask','respirator','gas mask','air purifying respirator',
  'safety harness','fall protection','safety rope','lifeline',
  'safety cone','traffic cone','road cone','delineator',
  'safety barrier','crowd control barrier','stanchion','rope barrier',
  'reflective vest','high visibility vest','safety jacket',
  'steel toe boots','safety boots','work boots','rubber boots',
  'work gloves','cut resistant gloves','heat resistant gloves',
  'chemical resistant gloves','disposable gloves',
  'apron','lab coat','coverall','boilersuit','jumpsuit',
  'hair net','beard net','shoe cover','boot cover',
  'cleaning supplies','janitorial supplies','housekeeping supplies',
  'office supplies','school supplies','art supplies',
  'medical supplies','laboratory supplies','industrial supplies',
  'agricultural supplies','farming supplies','gardening supplies',
  'construction supplies','building materials','hardware supplies',
  'electrical supplies','plumbing supplies','hvac supplies',
  'automotive supplies','vehicle supplies','fleet supplies',
  'food service supplies','catering supplies','kitchen supplies',
  'hospitality supplies','hotel supplies','restaurant supplies',
  'retail supplies','store supplies','shop supplies',
  'warehouse supplies','logistics supplies','shipping supplies',
  'packaging supplies','wrapping supplies','boxing supplies',
];

const hits = [];
for (const item of SUPPLY_ITEMS) {
  if (isOffensive(item)) {
    const token = normalize(item);
    for (const blocked of BLOCKED) {
      if (fuzzyContains(token, blocked)) {
        hits.push({ item, blocked });
        break;
      }
    }
  }
}

if (hits.length === 0) {
  console.log('ALL CLEAR - No false positives found.');
} else {
  console.log('FALSE POSITIVES FOUND (' + hits.length + '):');
  hits.forEach(h => console.log('  [' + h.item + '] blocked by: [' + h.blocked + ']'));
}
